### ISSUE TITLE
TweeParser + Handlebarsjs  

### ISSUE THREAD

**Issue by miguelcarvajal** [VincentLoy/jquery.tweetParser#11]
Hello,

Thanks for this great tool. I am trying to parse tweets from Google Spreadsheets into html using Tabletop.js + Handlebarsjs. Once I parse the tweet into Handlebar template the
`<p class="tweet">This is my awesome text only tweet ! #web #twitter @twitter http://www.twitter.com/ !!</p>`
the great tweetParser.js effect doesn't work. Do you know how can I fix this? 

Thanks!

**Comment by VincentLoy** [comment]
Hi miguel ! Can you tell me how did you initialized tweetParser in your webpage and which version of tweetParser are you using with ?

However, would this may be caused because tweetParser is loaded before that your template is generated ?
If it's the case, you may try to load tweetParser once everything is loaded into your page like so :+1: 

``` html
<!-- some code here -->

<p class="tweet"> this is a nice tweet #chido </p>

<!-- some code here -->
```

``` javascript
(function () {
    // your js logic stuff

    window.setTimeout(function () {
        tweetParser('.tweet');
    }, 0);
}());
```

Hope it'll help.

**Comment by miguelcarvajal** [comment]
Thanks, @VincentLoy. I have tried your solution, but it is still not working. Tweetparser is loaded after everything is loaded. The handlebars template that I am using is this one:

```
<div id="content"></div>    
<script id="cat-template" type="text/x-handlebars-template">
<p class="tweet">This is my awesome text only tweet ! #web #twitter @twitter http://www.twitter.com/ !!</p>
<p class="tweet">{{Status}}</p>
</script>
```

None of the _tweets_ work under the `cat-template` from Handlebarjs. If I put them outside, the do work.

I am using this  `tweetParser.js v2.2.0` with your code above and the one in the example. Both seem to work under _html_ but not under this _handlebars_ template:

```
<script type="text/javascript">
      var public_spreadsheet_url = 'https://docs.google.com/spreadsheets/d/1_uOy7-BLbB3AE5qTxnU_Z6zIKnwzN88iq_wPCP4NLmA/pubhtml';
      $(document).ready( function() {
        Tabletop.init( { key: public_spreadsheet_url,
                         callback: showInfo,
                         parseNumbers: true } );
      });

      function showInfo(data, tabletop) {
        var source   = $("#cat-template").html();
        var template = Handlebars.compile(source);
        $.each( tabletop.sheets("Cats").all(), function(i, cat) {
          var html = template(cat);
          $("#content").append(html);
        });
      }
</script>
```

And finally this is the tweetParser set up:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/0.0.1/prism.min.js"></script>
<script src="tweetparser.js"></script>
<script>
      window.setTimeout(function () {
        tweetParser('.tweet');
    }, 0);
</script> 
```

Thanks for your help.

**Comment by VincentLoy** [comment]
mmmh ok, I made some tests with mustache.js that provide similar stuff like handlebars (for templates rendering) and I reproduce the same bug. 

So, does handlebars provide a callback function on template rendering end ? I think that is the solution. Because When I run this code : 

``` javascript
window.setTimeout(function () {
    tweetParser('.tweet');
}, 1500);
```

it work perfectly. I really think that you have to wait the template rendering end before calling tweetParser :)

**Comment by miguelcarvajal** [comment]
Wow! It works! Thank you very much. This is really saving me a lot of time! 

Best regards!

**Comment by VincentLoy** [comment]
Nice ! Saludos !
